### PR TITLE
Fix parse_skipped for parsing zeroes

### PR DESCRIPTION
**Pull request by orlp**
Fixes https://github.com/RoDmitry/atoi_simd/issues/9.

### CODE REVIEW

**Comment by RoDmitry** [comment]
Thank you!

**Comment by orlp** [comment]
@RoDmitry Pretty sure the compiler would generate identical code for that.

**Comment by RoDmitry** [comment]
Sadly, but it's not. And sometimes I am very disappointed in a compiler, because I had to even do [this](https://github.com/RoDmitry/atoi_simd/blob/5e156ee9d6cef90928e0cabdf2e2dbd5b1225421/src/simd/sse_avx.rs#L189)

**Comment by RoDmitry** [comment]
Also functions with only one line of code, you would think that they're gonna be inlined, but it's not. It would not hurt to actually write `#[inline]`.

**Pull request merged**
