### PR TITLE
Add exhaustive roundtrip tests for small integers

### PR DESCRIPTION
**Pull request by Shnatsel**

### CODE REVIEW

**Comment by RoDmitry** [comment]
There is no `std` in tests. Use `ArrayString` instead of `Vec`

**Comment by Shnatsel** [comment]
Sadly `ArrayString` implements `io::Write` instead of `fmt::Write` and gates it on the `std` feature, so there's no way to write to it in a `#[no_std]` environment.

I had to pull in the `numtoa` crate instead of using the standard library to make this work.

**Comment by RoDmitry** [comment]
Also it has `fmt::Write` implemented

**Comment by Shnatsel** [comment]
These are docs for the wrong crate. They are for `arraystring` crate while the tests use `ArrayString` type from the `arrayvec` crate.

Also, once I enable the `std` feature, the code is no longer `#[no_std]`. 

Besides all that, I cannot fathom why would you want `no_std` in tests of all the places. The main crate - sure, so you could use it in a kernel or in firmware or on a microcontroller, but why in the tests?

**Comment by RoDmitry** [comment]
Huh, wrong link)
How else would I test that `no_std` is implemented correctly?

**Comment by Shnatsel** [comment]
https://blog.dbrgn.ch/2019/12/24/testing-for-no-std-compatibility/

**Comment by RoDmitry** [comment]
I still don't understand, what's wrong with using `ArrayString` in tests?

**Comment by Shnatsel** [comment]
Nothing, I guess? I just could not find a way to use the standard library integer-to-string implementation with it. 

And since I'm using a third-party crate that writes to a `&mut [u8]` instead of any kind of string, I don't even need ArrayString in the first place, so I didn't use it in the tests I added.

**Comment by RoDmitry** [comment]
Are you sure that we need such exhaustive tests? If so, then why only max u16?)

**Comment by Shnatsel** [comment]
These tests execute in under a second and enumerate all possible inputs, so I think they are a great addition.

I did not go for 32-bit numbers because those take minutes. The fuzzer will be a better fit for 32-bit numbers, I think, since it will also try various invalid inputs and check that they don't cause memory safety issues. It is very common for unsafe code to blow up on exotic inputs that don't naturally occur but can be deliberately crafted by an attacker, so testing all the valid inputs doesn't quite get us all the way.

**Comment by RoDmitry** [comment]
Ok, let it be then. Thanks &#128588; &#127881;

**Pull request merged**
